### PR TITLE
Change Lambda Functions to work

### PR DESCRIPTION
**Pull request by ssakhavi**
I managed to solve the problem causing the error:
`Exception has occurred: TypeError can't pickle _thread.RLock objects`

The lambda functions needed to be changed to not include any functions in the arguments.

### CODE REVIEW

**Comment by bonlime** [comment]
@ssakhavi  Thanks for your PR! Merged.

**Comment by pluniak** [comment]
I pulled the TF2 version of this repo today and the pickle error still occurs. Only after replacing model.py with @ssakhavi's it works.

**Comment by FelipeR2U** [comment]
> I pulled the TF2 version of this repo today and the pickle error still occurs. Only after replacing model.py with @ssakhavi's it works.

I'm having the same situation. Only by copy pasting the `model.py` by @ssakhavi  I can save the xception model.

**Comment by brianmanderson** [comment]
I've put in a merge to fix this with TF2, #137

**Pull request merged**
